<a href="https://colab.research.google.com/github/nimaghasemilearning/PyTorch-Tutorial/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [3]:
np1 = np.random.rand(3,4)
np1

array([[0.66009137, 0.60925556, 0.71016981, 0.70550423],
       [0.20507583, 0.93213095, 0.70795213, 0.18172382],
       [0.97689157, 0.91212037, 0.76426097, 0.13821005]])

In [4]:
np1.dtype

dtype('float64')

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.7187,  2.1354,  0.4567, -1.6196],
        [-1.7635, -0.3679,  0.8611,  1.1939],
        [ 1.7249,  0.2060, -0.0163,  1.8820]])

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6601, 0.6093, 0.7102, 0.7055],
        [0.2051, 0.9321, 0.7080, 0.1817],
        [0.9769, 0.9121, 0.7643, 0.1382]], dtype=torch.float64)