<a href="https://colab.research.google.com/github/nimaghasemilearning/PyTorch-Tutorial/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [3]:
#adition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
#adition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
#subtract
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [6]:
#sub function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [7]:
#multiple
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [8]:
#mul longhand
torch.multiply(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [9]:
#divition
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [10]:
#div longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
#remainder modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [12]:
#rem longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [13]:
#exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [14]:
#another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [15]:
#reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [18]:
tensor_a

tensor([1, 2, 3, 4])

In [21]:
#tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [22]:
tensor_a

tensor([ 6,  8, 10, 12])